config-version: "@VERSION@"

# For updating the plugin automatically
updater:
  auto-check: true
  auto-install: true

# For sending anonymous usage data to us for future improvements
metrics:
  enable: true