config-version: "@VERSION@"

# For updating the plugin automatically
updater:
  auto-check: true
  auto-install: false

# For sending anonymous usage data to us for future improvements
metrics:
  enable: true