name: CommandIt
version: "@VERSION@"
description: 'Allows players to bind Lua scripts to blocks'
authors: [zonedabone, CJxD]

main: org.zone.commandit.CommandIt

depend: [Vault]
softdepend: [Multiverse-Core]

commands:
  commandit:
    aliases: [cmdit, cmdi]
    description: CommandIt commands.
    usage: |
        /commandit <linenumber> <text>
               Add a line with one command or a line of text to the clipboard.
        /commandit batch
               Changes your state into batch mode for doing bigger tasks quicker.
        /commandit clear
               Clear your CommandIt clipboard.
        /commandit copy
               Copy a command block to clipboard (the command lines associated with it).
               Note: You need permission to create a sign in order to read.
        /commandit edit
               Edit a command block in live mode.
        /commandit insert <linenumber> <text>
               Insert a line into an existing command block.
               Changes are stored in clipboard: click a sign to apply.
        /commandit read
               Read a command block (the command lines associated with it).
               Note: You need permission to create a sign in order to read.
        /commandit redstone
               Toggle whether the command block can be triggered by redstone
               Off by default
        /commandit reload
               Reload CommandIt.
        /commandit remove
               Remove a command block.
        /commandit update
               Update CommandIt to latest version.
               /commandit update check
                       Check for updates only.
               /commandit update force
                       Force an update.
        /commandit view
               View the contents of your clipboard.
permissions:
    commandit.*:
        description: Gives access to all CommandIt commands
        children:
            commandit.create.*: true
            commandit.remove: true
            commandit.use.*: true
            commandit.group.*: true
            commandit.update: true
            commandit.save: true
            commandit.reload: true
            commandit.edit: true
        default: op
    commandit.create.*:
        description: Gives access CommandIt sign creation commands
        children:
            commandit.create.regular: true
            commandit.create.super: true
            commandit.create.redstone: true
            commandit.create.op: true
    commandit.save:
        description: Allows saving CommandIt without reloading
        default: false;
    commandit.reload:
        description: Reloads CommandIt and all configuration
        default: false;
    commandit.use.*:
        description: Gives access to CommandIt sign use
        default: true
        children:
            commandit.use.regular: true
            commandit.use.super: true
    commandit.create.regular:
        description: Allows you to create a regular command block
        default: false
    commandit.create.super:
        description: Allows you to create a super command block
        default: false
    commandit.create.redstone:
        description: Allows you to create redstone-activated signs
        default: false
    commandisgns.create.op:
        description: Allows you to create op-level CommandIt
        default: false
    commandit.remove:
        description: Allows you to remove a command block
        default: false
    commandit.use.regular:
        description: Allows you to use a regular command block
        default: false
    commandit.use.super:
        description: Allows you to use a super command block
        default: false
    commandit.group.*:
        description: Allows you to use all group commands
        default: false
    commandit.update:
        description: Shows this player CommandIt updates and allows them to update
        default: false
    commandit.edit:
        description: Allows editing of CommandIt
        default: false