config-version: "${project.version}"

# If you prefer using a database over YAML, you can enable SQL support
database:
  enable: false
  
  # Acceptable drivers:
  # - com.mysql.jdbc.Driver
  # - org.sqlite.JDBC
  driver: com.mysql.jdbc.Driver
  
  # Acceptable isolation modes:
  # - SERIALIZABLE
  # - REPEATABLE_READ
  # - READ_COMMITTED
  # - READ_UNCOMMITTED
  isolation: SERIALIZABLE
  
  username: {USERNAME}
  password: {PASSWORD}
  
  # URL Example (default): mysql://127.0.0.1:3306/minecraft
  url: mysql://{IP}:{PORT}/{DATABASENAME}

# For updating the plugin automatically
updater:
  auto-check: true
  auto-install: true

# For sending anonymous usage data to us for future improvements
metrics:
  enable: true