package org.zone.commandit.util;

public enum PlayerState {
	BATCH_ENABLE, BATCH_INSERT, BATCH_READ, BATCH_REDSTONE, BATCH_REMOVE, BATCH_TOGGLE, COPY, EDIT, EDIT_SELECT, ENABLE, INSERT, READ, REDSTONE, REMOVE, TOGGLE;
}
